// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scoreboard} from '../models';

export function GetScoreBoard():Promise<scoreboard.Scoreboard>;

export function SaveEntireScoreboard():Promise<void>;

export function SetBestOf(arg1:number):Promise<void>;

export function SetPlayerName(arg1:number,arg2:string):Promise<void>;

export function SetRoundName(arg1:string):Promise<void>;

export function SetScore(arg1:number,arg2:number):Promise<void>;
