// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetScoreBoard() {
  return window['go']['scoreboard']['Scoreboard']['GetScoreBoard']();
}

export function SaveEntireScoreboard() {
  return window['go']['scoreboard']['Scoreboard']['SaveEntireScoreboard']();
}

export function SetBestOf(arg1) {
  return window['go']['scoreboard']['Scoreboard']['SetBestOf'](arg1);
}

export function SetPlayerName(arg1, arg2) {
  return window['go']['scoreboard']['Scoreboard']['SetPlayerName'](arg1, arg2);
}

export function SetRoundName(arg1) {
  return window['go']['scoreboard']['Scoreboard']['SetRoundName'](arg1);
}

export function SetScore(arg1, arg2) {
  return window['go']['scoreboard']['Scoreboard']['SetScore'](arg1, arg2);
}
