// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeStr() {
  return window['go']['main']['App']['ChangeStr']();
}

export function GetStr() {
  return window['go']['main']['App']['GetStr']();
}

export function WriteStringToFile(arg1, arg2) {
  return window['go']['main']['App']['WriteStringToFile'](arg1, arg2);
}
