// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeStr():Promise<void>;

export function GetStr():Promise<string>;

export function WriteStringToFile(arg1:string,arg2:string):Promise<void>;
